### ISSUE TITLE
onic Image Loader  - ionic4 error

### ISSUE THREAD

**Issue by EvgenyKL** [paulstelzer/innomobile-library#1]
hi 

I have ionic4 app 
when I using Ionic Image Loader (Ionic 4+) I get this error

[ng] ERROR in ./node_modules/@innomobile/ionic-image-loader/fesm5/innomobile-ionic-image-loader.js
[ng] Module not found: Error: Can't resolve '@ionic/angular/dist/providers/platform' in 'D:\Inetpub\Real-Manager-Ionic-Client\node_modules\@innomobile\ionic-image-loader\fesm5'

**Comment by ctmartinez1992** [comment]
I have this exact same error :(

**Comment by paulstelzer** [comment]
The image loader isn't part of this repo anymore because the original one was updated since then, so I removed it here. Take a look at https://github.com/zyra/ionic-image-loader
